- name: Variables from task level
  hosts: web
  become: yes
  vars:
    course: "DevOps with AWS"
    Trainer: "Shiva kumar"
    Duration: "6 Months"
  tasks:
  - name: Variables from task level
    vars:
      course: "DevOps with Azure from task level"
    ansible.builtin.debug:
      msg: "Hi, Im learning {{course}} and Duration is {{Duration}} with Trainer {{Trainer}}"