- name: variables from inventory
  hosts: web
  become: yes
  tasks:
  - name: Variables from inventory
    ansible.builtin.debug:
      msg: "Hi, I'm learning {{course}} and Duration is {{Duration}} and Trainer is {{Trainer}}"