- name: Variables preference check by ansible
  hosts: web
  become: yes
  vars:
    Associate: "Arun from Play level"
    jobtitle: "Software Engineer from Play level"
  # vars_files:
  # - variables.yaml
  # vars_prompt:
  # - name: Associate
  #   prompt: Prompt Level Pls enter Your Name
  #   private: false
  # - name: jobtitle
  #   prompt: Prompt Level Pls Enter Your jobtitle
  #   private: false # or true
  tasks:
  - name: variables preference check by ansible
    vars:
      # Associate: "Arun from Task level"
      # jobtitle: "Software Engineer from Task level"
    ansible.builtin.debug:
      msg: "Hello {{Associate}}, Your Job Title is {{jobtitle}}"