- name: tags example
  hosts: localhost
  become: yes
  tasks:
  - name: ping the server
    ansible.builtin.ping:
  
  - name: print message
    ansible.builtin.debug:
      msg: "Hi this is DevOps platform"
    tags:
    - devops
  
  - name: print message
    ansible.builtin.debug:
      msg: "Hi this is Aws platform"
    tags:
    - aws